#!/usr/bin/env bash
# Create the format-a-parity-ctest branch on the oops fork: the C++
# evaluation-parity test that welds oops::NonGaussianDensity to the
# stable_DOEE Python exporter through parity_fixtures.json. Run on the
# machine that holds the oops checkout (the VM).
#
#   bash make_parity_branch.sh [path-to-oops-checkout]
#
# The patch carries the test code and CMake wiring; the fixtures file
# itself is COPIED from its canonical committed location
# (jedi_export/parity_fixtures.json) so there is exactly one literal
# source of truth. Unlike the PFF branch, this test should be GREEN on
# the first run -- its references ARE the fixture numbers.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PATCH="$HERE/format_a_parity.patch"
FIXTURES="$HERE/../parity_fixtures.json"
[ -f "$PATCH" ] || { echo "patch not found next to this script"; exit 1; }
[ -f "$FIXTURES" ] || { echo "canonical parity_fixtures.json not found"; exit 1; }

OOPS="${1:-}"
if [ -z "$OOPS" ]; then
  OOPS="$(find "$HOME" -maxdepth 9 -name PFF.h \
          -path "*src/oops/assimilation*" 2>/dev/null \
          | head -1 | sed 's#/src/oops/assimilation/PFF.h##')"
fi
[ -n "$OOPS" ] && [ -d "$OOPS/.git" ] || {
  echo "oops checkout not found; pass it explicitly:"
  echo "  bash make_parity_branch.sh /path/to/oops"
  exit 1
}

cd "$OOPS"
echo "oops checkout: $OOPS"

git config user.email > /dev/null 2>&1 || {
  echo "git identity is not set on this machine; set one first"; exit 1; }

git fetch origin
git checkout -f -B format-a-parity-ctest origin/nongaussian-costjo
git apply --check "$PATCH"
git apply "$PATCH"
cp "$FIXTURES" src/test/testinput/parity_fixtures.json
git add src/CMakeLists.txt src/test/assimilation/FormatAParity.h \
        src/test/assimilation/FormatAParity.cc \
        src/test/testinput/parity_fixtures.json
git commit -m "Evaluation-parity ctest for the Format A interface

oops_assimilation_formata_parity: NonGaussianDensity score and
evolvingVariance replayed against reference tables generated by the
stable_DOEE Python exporter from the analytic menu densities (gaussian,
heavy, skewed, laplace), 23 branch-covering points per density, tol
1e-9. Fixtures are canonical in stable_DOEE
(jedi_export/make_parity_fixtures.py, --check for byte stability);
regenerate there, copy here."

cat << 'EOT'

Branch format-a-parity-ctest is ready. Remaining steps in the build
tree (the CMakeLists change makes make rerun cmake automatically):

  cd ~/jedi/src/build/oops
  make -j4 2>&1 | tail -5
  ctest -R oops_assimilation_formata_parity --output-on-failure

This test should be GREEN immediately: its references are the fixture
numbers themselves. A failure is a FINDING, not a regeneration case --
it means the two evaluators genuinely disagree on some branch, and the
per-point mismatch lines in the log say exactly where. Then:

  cd <oops>
  git push -u origin format-a-parity-ctest
EOT
